import { MigrationInterface, QueryRunner } from 'typeorm';

export class AutoGenerated1749937131316 implements MigrationInterface {
  name = 'AutoGenerated1749937131316';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "links" DROP CONSTRAINT "UQ_4bed2865d72534f7b9912d1655c"`
    );
    await queryRunner.query(`ALTER TABLE "links" DROP COLUMN "short_url"`);
    await queryRunner.query(
      `ALTER TABLE "links" ADD "short_code" character varying(6) NOT NULL`
    );
    await queryRunner.query(
      `ALTER TABLE "links" ADD CONSTRAINT "UQ_e310b9137c352dac8806d5ccbd7" UNIQUE ("short_code")`
    );
    await queryRunner.query(
      `ALTER TABLE "links" ADD "click_count" integer NOT NULL DEFAULT '0'`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "links" DROP COLUMN "click_count"`);
    await queryRunner.query(
      `ALTER TABLE "links" DROP CONSTRAINT "UQ_e310b9137c352dac8806d5ccbd7"`
    );
    await queryRunner.query(`ALTER TABLE "links" DROP COLUMN "short_code"`);
    await queryRunner.query(
      `ALTER TABLE "links" ADD "short_url" character varying(6) NOT NULL`
    );
    await queryRunner.query(
      `ALTER TABLE "links" ADD CONSTRAINT "UQ_4bed2865d72534f7b9912d1655c" UNIQUE ("short_url")`
    );
  }
}
