version: '3.8'

services:
  app:
    build: .
    container_name: teddy-links-app
    restart: always
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    networks:
      - teddy-net

  db:
    image: postgres:15-alpine
    container_name: teddy-links-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_HOST_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teddy-net

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: teddy-links-jaeger
    restart: always
    ports:
      - '16686:16686'
      - '4318:4318'
    networks:
      - teddy-net

  prometheus:
    image: prom/prometheus:latest
    container_name: teddy-links-prometheus
    restart: always
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - '${PROMETHEUS_PORT}:9090'
    networks:
      - teddy-net

  grafana:
    image: grafana/grafana:latest
    container_name: teddy-links-grafana
    restart: always
    ports:
      - '${GRAFANA_PORT}:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - teddy-net

networks:
  teddy-net:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
