apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
  labels:
    app: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: YOUR_APP_IMAGE_PLACEHOLDER 
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: NODE_ENV
          value: "production"

        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: app-config-secret 
              key: DATABASE_HOST
        - name: DATABASE_HOST_PORT
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: DATABASE_HOST_PORT
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: DATABASE_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: DATABASE_NAME
        - name: DATABASE_TYPE
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: DATABASE_TYPE
        
        - name: USER_AUTH_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: USER_AUTH_JWT_SECRET
       
        - name: OTEL_ENABLED
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: OTEL_ENABLED

        - name: OTEL_SERVICE_NAME
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: OTEL_SERVICE_NAME

        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: OTEL_EXPORTER_OTLP_ENDPOINT

       
        - name: METRICS_ENABLED
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: METRICS_ENABLED

        - name: GRAFANA_PORT
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: GRAFANA_PORT

        - name: PROMETHEUS_PORT
          valueFrom:
            secretKeyRef:
              name: app-config-secret
              key: PROMETHEUS_PORT

        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Debugging DB Variables:"
            echo "DATABASE_USERNAME: $DATABASE_USERNAME"
            echo "DATABASE_PASSWORD: $DATABASE_PASSWORD"
            echo "DATABASE_HOST: $DATABASE_HOST"
            echo "DATABASE_HOST_PORT: $DATABASE_HOST_PORT"
            echo "DATABASE_NAME: $DATABASE_NAME"
            echo "DATABASE_URL (se definida): $DATABASE_URL"
            echo "Starting Node.js application..."
            node dist/src/main.js

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"