apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s # A cada 15 segundos ele vai 'raspar' métricas

    scrape_configs:
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: '${1}:10255' #kubelet metrics port, adjust if different
            target_label: __address__
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: 'kubernetes.default.svc.cluster.local:443' # For GKE, scrape kubelet via API server
            target_label: __address__
            action: replace
          - source_labels: [__meta_kubernetes_node_name]
            regex: '(.*)'
            target_label: kubernetes_node_name
            replacement: '$1'
          - source_labels: [__meta_kubernetes_node_name]
            action: replace
            regex: 'gke-(.*)' # For GKE
            target_label: instance
            replacement: '$1'
        scheme: https
        tls_config:
          insecure_skip_verify: true # Não recomendado em produção sem CA configurada
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      - job_name: 'kubernetes-pods' # Scrape para pods (sua aplicação)
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: (.+):(?:\d+);(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
          # Para sua aplicação (assumindo que ela exponha métricas em /metrics na porta 4000)
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            regex: 'url-shortener-deployment-(.*)' # Substitua pelo padrão de nome do seu pod
            target_label: job
            replacement: 'url-shortener-app'
          - source_labels: [__address__]
            regex: '(.+)'
            replacement: '$1:4000' # Sua aplicação expõe métricas na porta 4000
            target_label: __address__
            action: replace